### ISSUE TITLE
Feature request: Element type on select

### ISSUE THREAD

**Issue by Hbaldwin** [VoltSim/VoltSim#29]
It would be really nice for newbies like me if when i selected a component a label with the type of component was ma lde visible. Possibly right above the toolbox bar on the bottom.

**Comment by voltsimapp** [comment]
Hi @Hbaldwin , Currently if you enable the multimeter it would show the name of the selected component along with some other info about the component. 

![mm](https://user-images.githubusercontent.com/94251430/206860451-aec5fa68-77a0-4496-8a72-d6158ca4a175.jpeg)

Was this what you were looking for? 
If so, maybe we can improve the UX so that this is more obvious. Enable this by default maybe?

**Comment by Hbaldwin** [comment]
That is very much what i was looking for. It would be nice to be able to
just have the name. But this is great and very helpful. Feel free to close
this request. I tgink default enabled might be useful but by no means
neccesary. Thanks for your help, and work on such a great project!!!!

**Comment by Hbaldwin** [comment]
The multimeter can accomplish this well, though it takes up a bit more space than neccesary for just the name. Closing for that reason.
